dist: trusty
sudo: required
language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
before_install:
- yarn
script:
- yarn lint
- yarn flow
- yarn test
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then yarn appr; fi'
- yarn coverage
